--- 
jobs: 
  build: 
    docker: 
      - 
        auth: 
          password: DOCKERHUB_PASS
          username: mydockerhub_user
        image: "circleci/python:3.6"
    steps: 
      - checkout
      - 
        run: "pip install -r requirements/dev.txt"
version: 2











